// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' 

show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvMSkOyAcmnVajxtnT44Bgcn21xN2bo8',
    appId: '1:100007820245:web:98fa71314aaccf11d79b5c',
    messagingSenderId: '100007820245',
    projectId: 'laza-ecomm',
    authDomain: 'laza-ecomm.firebaseapp.com',
    storageBucket: 'laza-ecomm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFIoKm0iLaXXMbbzOigZ7LcXS14W9E2hg',
    appId: '1:100007820245:android:ce725c7ed1cba2e1d79b5c',
    messagingSenderId: '100007820245',
    projectId: 'laza-ecomm',
    storageBucket: 'laza-ecomm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxNGTBxTzHftcmrK3h1q7oP2rBHEyibXg',
    appId: '1:100007820245:ios:fbeca3a80c0d3758d79b5c',
    messagingSenderId: '100007820245',
    projectId: 'laza-ecomm',
    storageBucket: 'laza-ecomm.appspot.com',
    iosBundleId: 'com.example.lazapayV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxNGTBxTzHftcmrK3h1q7oP2rBHEyibXg',
    appId: '1:100007820245:ios:06304f9e34c249e3d79b5c',
    messagingSenderId: '100007820245',
    projectId: 'laza-ecomm',
    storageBucket: 'laza-ecomm.appspot.com',
    iosBundleId: 'com.example.lazapayV2.RunnerTests',
  );
}
